/*
 * generated by Xtext
 */
package org.efry.z80editor.validation

import org.eclipse.xtext.validation.Check
import org.efry.z80editor.z80.SignedByteOffset
import org.efry.z80editor.z80.Z80Package
import org.efry.z80editor.z80.BitType

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class Z80Validator extends AbstractZ80Validator {

	@Check
	def checkOffsetRange(SignedByteOffset offset) {
		var value = offset.value;
		if ("-".equals(offset.sign)) {
			value = -value;
		}
		if (value < -128 || value > 127) {
			error('Signed offset must be in the range (-128 to +127)', Z80Package.Literals.SIGNED_BYTE_OFFSET__VALUE)
		}
	}
	
	@Check
	def checkBitType(BitType type) {
		if (type.value > 7) {
			error('Bit type must be in the range (0 to 7)', Z80Package.Literals.BIT_TYPE__VALUE);
		}
	}
}
