/*
 * generated by Xtext
 */
package org.efry.z80editor.ui.contentassist

import org.efry.z80editor.ui.contentassist.AbstractZ80ProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class Z80ProposalProvider extends AbstractZ80ProposalProvider {
}
