/*
 * generated by Xtext 2.20.0
 */
package org.efry.z80editor.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class Z80ProposalProvider extends AbstractZ80ProposalProvider {
}
