/*
 * generated by Xtext
 */
package org.efry.z80editor;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Z80RuntimeModule extends org.efry.z80editor.AbstractZ80RuntimeModule {

}
