/*
 * generated by Xtext 2.20.0
 */
package org.efry.z80editor


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class Z80RuntimeModule extends AbstractZ80RuntimeModule {
}
