/*
 * generated by Xtext 2.20.0
 */
package org.efry.z80editor


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Z80StandaloneSetup extends Z80StandaloneSetupGenerated {

	def static void doSetup() {
		new Z80StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
