/*
 * generated by Xtext
 */
package org.efry.z80editor;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class Z80StandaloneSetup extends Z80StandaloneSetupGenerated{

	public static void doSetup() {
		new Z80StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

