/*
 * generated by Xtext
 */
package org.efry.z80editor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Z80UiModule extends org.efry.z80editor.ui.AbstractZ80UiModule {
	public Z80UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
