/*
 * generated by Xtext 2.20.0
 */
package org.efry.z80editor.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class Z80UiModule extends AbstractZ80UiModule {
}
